### ISSUE TITLE
Adding experimental modules (WNdb / lapack) to README.md

### ISSUE THREAD

**Issue by SphinxKnight** [DavidBruant/Twitter-Assistant#111]
Some extra-npm modules are needed:
- WNdb
- lapack

If they are not installed, building fails.
Since they are mentioned as "experimentally" integrated in natural and in natural/sylvester, they (maybe) shouldn't be added in `package.json`. However mentioning them in the README for setup could be useful.

Using:

```
>npm install WNdb
>npm install lapack
```

was enough for me to get them installed and to be able to properly run `npm run build`

**Comment by DavidBruant** [comment]
I chose to [ignore them](https://github.com/DavidBruant/Twitter-Assistant/blob/257967fd8a1fd81f98d7cf04debe46104d0ba491/package.json#L19) in `npm run watch`. I should do the same for `npm run build`
